import fs from "node:fs";
import path from "node:path";
import { findRoot, readJson } from "./paths.js";

const TEXT = /\.(html|php|css|js|md|txt|json|blade\.php|example)$/i;

export function loadBrand(root = findRoot()) {
  const file = path.join(root, "config", "brand.json");
  if (!fs.existsSync(file)) {
    return {
      name: "AppSeed",
      url: "https://appseed.dev",
      tagline: "Generated by AppSeed",
      credit: "Built with AppSeed",
      show: true,
    };
  }
  return { ...loadDefaults(), ...readJson(file) };
}

function loadDefaults() {
  return {
    name: "AppSeed",
    url: "https://appseed.dev",
    tagline: "Generated by AppSeed",
    credit: "Built with AppSeed",
    show: true,
  };
}

export function brandTokens(brand) {
  const credit = brand.show === false ? "" : brand.credit;
  return {
    "{{APPSEED_NAME}}": brand.name || "AppSeed",
    "{{APPSEED_URL}}": brand.url || "#",
    "{{APPSEED_TAGLINE}}": brand.show === false ? "" : brand.tagline || "",
    "{{APPSEED_CREDIT}}": credit,
  };
}

export function applyBrand(destRoot, brand) {
  const tokens = brandTokens(brand);
  walk(destRoot, (file) => {
    if (!TEXT.test(file) && !file.endsWith(".blade.php")) return;
    let text = fs.readFileSync(file, "utf8");
    let next = text;
    for (const [from, to] of Object.entries(tokens)) {
      next = next.split(from).join(to);
    }
    if (next !== text) fs.writeFileSync(file, next);
  });
}

function walk(dir, visit) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (["node_modules", "vendor", ".git", ".next"].includes(entry.name)) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, visit);
    else if (entry.isFile()) visit(full);
  }
}
