import fs from "node:fs";
import path from "node:path";

export function writeGettingStarted(destRoot, options) {
  const { name, stack, features, addons = [], dashboard, landing, theme, docker, brand } = options;
  const credit = brand?.show === false ? "" : `${brand?.tagline || "Generated by AppSeed"}${brand?.url ? ` (${brand.url})` : ""}`;
  const install = (stack.run?.install || []).map((c) => `  ${c}`).join("\n");
  const dockerfiles = docker?.dockerfiles?.length
    ? docker.dockerfiles.map((file) => `- ${file}`).join("\n")
    : "- none (images only)";
  const images = docker?.images?.length ? docker.images.join(", ") : "none";
  const body = `# ${name}

${credit}

- Stack: ${stack.id}
- Features: ${features.length ? features.join(", ") : "none"}
- Addons: ${addons.length ? addons.join(", ") : "none"}
- Dashboard: ${dashboard}
- Landing: ${landing}
- Theme: ${theme}

## Install

\`\`\`bash
${install}
\`\`\`

## Run

\`\`\`bash
${stack.run?.dev || "echo 'no dev command'"}
\`\`\`

## Docker

Dockerfiles (only services we build):

${dockerfiles}

Public images: ${images}

\`\`\`bash
${stack.run?.docker || "docker compose up"}
\`\`\`
`;

  const file = path.join(destRoot, "GETTING_STARTED.md");
  fs.writeFileSync(file, body);
  return "GETTING_STARTED.md";
}
