import { addRemoteAndPush, initLocalRepo } from "./git.js";

async function gh(path, token, { method = "GET", body } = {}) {
  const res = await fetch(`https://api.github.com${path}`, {
    method,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${token}`,
      "User-Agent": "appseed-cli",
      "X-GitHub-Api-Version": "2022-11-28",
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) {
    throw new Error(data.message || `GitHub API ${res.status} on ${path}`);
  }
  return data;
}

export async function publishToGithub({ destRoot, name, token, isPrivate = true, description }) {
  if (!token) {
    throw new Error("Set GITHUB_TOKEN (or pass --token) to create a GitHub repo.");
  }

  const user = await gh("/user", token);
  const repo = await gh("/user/repos", token, {
    method: "POST",
    body: {
      name,
      private: isPrivate,
      description: description || `Generated by AppSeed`,
      auto_init: false,
    },
  });

  initLocalRepo(destRoot);
  const pushUrl = `https://x-access-token:${token}@github.com/${user.login}/${repo.name}.git`;
  addRemoteAndPush(destRoot, pushUrl);

  return {
    url: repo.html_url,
    clone: `git clone git@github.com:${user.login}/${repo.name}.git`,
    cloneHttps: repo.clone_url,
    owner: user.login,
    name: repo.name,
  };
}
